---

- name: Copy to var-www on hosts
  hosts: all
  gather_facts: false
  tasks:
    - ansible.posix.synchronize:
        src: dist/
        dest: /var/www/html/

        group: false
        perms: false
        rsync_timeout: 10
        times: false

...
